#!/bin/bash
help()
{
  echo -e "1337sp34k -f \"translate from 1337sp34k text\""
  echo -e "1337sp34k -t \"translate to 1337sp34k text\""
}

tranlate()
{
  if [ "${#2}" -ne "${#3}" ]; then return 1; fi

  IFS='' read -ra fromArray <<< "$2"
  IFS='' read -ra toArray <<< "$3"

  result="$1"
  for curIndex in "${fromArray[@]}"
  do
    result="$(echo "$result" | tr "${fromArray[curIndex]}" "${toArray[curIndex]}")"
  done

  echo "$result"
}

if [ "$#" -lt 2 ] || ! [[ "$1" =~ ^(-f|-t)$ ]]; then help; exit 2; fi

if [ "$1" == "-t" ]; then tranlate "$2" "aeiou" "4310_" | cat;
else tranlate "$2" "4310_" "aeiou" | cat; fi
