#!/bin/bash
help()
{
  echo -e "translate \"abc\" \"klf\" \"text\""
  echo ""
  echo -e "translate \"a b c\" \"symbols symbols symbols\" \"text\""
  echo -e "translate -d \":\" \"a:b:c\" \"symbols:symbols:symbols\" \"text\""
  echo ""
  echo -e "translate \"symbols symbols c\" \"a symbols lol\" \"text\""
}

#arguments
if ! [[ "$#" =~ ^[1,2,4]$ ]]; then
  help
  exit 2
fi

delimeterUsed=false
delimeter=" "
arguments=("$@")

while getopts h?d: option
do
  case "${option}" in
    h)
    help
    exit 0
    ;;
    d)
    delimeterUsed=true
    delimeter=${OPTARG}
    ;;
  esac
done

for curArgIndex in $(seq $#)
do
  case "${arguments[curArgIndex]}" in
    -d)
      if [[ "$curArgIndex" -eq 0 ]]; then
      curArgIndex=$((curArgIndex+2)); else
      help
      exit 2
      fi
    ;;
    -*)
      help
      exit 2
    ;;
  esac
done

if [ "$delimeterUsed" = false ]; then
  spacesInFrom="$(echo "$1" | grep -o ' ' | wc -l )"
  spacesInTo="$(echo "$2" | grep -o ' ' | wc -l )"
else
  spacesInFrom=`echo "${3}" | awk -F"${delimeter}" '{print NF-1}'`
  spacesInTo=`echo "${4}" | awk -F"${delimeter}" '{print NF-1}'`
fi

if [ "$spacesInFrom" -eq 0 ] && [ "$spacesInTo" -eq 0 ]; then
  if [ "${#1}" -ne "${#2}" ]; then
    help
    exit 1
  fi
  delimeter=""
else
  if [ "$spacesInTo" -ne "$spacesInFrom" ]; then
    help
    exit 2
  fi
fi
#translation
