#!/bin/bash
help()
{
  echo -e "translate \"abc\" \"klf\" \"text\""
  echo ""
  echo -e "translate \"a b c\" \"symbols symbols symbols\" \"text\""
  echo -e "translate -d ":" \"a:b:c\" \"symbols:symbols:symbols\" \"text\""
  echo ""
  echo -e "translate \"symbols symbols c\" \"a symbols lol\" \"text\""
}

delimeterUsed=false
delimeter=" "
arguments=$@

for curArgIndex in "${arguments[@]}"
do
  case "${arguments[curArgIndex]}" in
    -h)
      help()
      exit 0
    ;;
    -d)
      delimeterUsed=true
      curArgIndex=$((curArgIndex+1))
      delimeter="${arguments[curArgIndex]}"
      curArgIndex=$((curArgIndex+1))
    ;;
    -*)
      help()
      exit 2
    ;;
  esac
done
