include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_redundant_argument_values: ignore
    flutter_style_todos: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    directives_ordering: false
    dangling_library_doc_comments: false
    always_use_package_imports: false
    public_member_api_docs: false
    sort_pub_dependencies: false
    document_ignores: false
    avoid_catches_without_on_clauses: false
    prefer_constructors_over_static_methods: false
