#!/bin/bash

currentYear="2020"

dateToFormat() {
  time="$(date +%H:%M)"
  IFS="/" read -ra arr <<< "$1"
  if [ $(tr -dc '/' <<<"$1" | wc -c) -eq 2 ]; then
    year="20${arr[2]}"; else year="$currentYear"; fi

  date --date="${arr[1]}/${arr[0]}/$year" "+%a %b %d $time %Y +0300"
}

git add -A
git commit --date="$(dateToFormat "$2")" -m "$1"
if [ "$#" -eq 3 ] && [ "$3" = "+" ]; then
 git push; fi
