#!/bin/bash
help()
{
  echo -e "1337sp34k -f \"translate from 1337sp34k text\""
  echo -e "1337sp34k -t \"translate to 1337sp34k text\""
}

tranlate()
{
  if [ "${#2}" -ne "${#3}" ]; then return 1; fi

  echo "$1" | tr "$2" "$3"
}

if [ "$#" -lt 2 ] || ! [[ "$1" =~ ^(-f|-t)$ ]]; then help; exit 2; fi

if [ "$1" == "-t" ]; then tranlate "$2" "aeiou" "4310_";
else tranlate "$2" "4310_" "aeiou"; fi
