#!/bin/bash
help()
{
  echo -e "kekSpeak -f \"translate from kekSpeak text\""
  echo -e "kekSpeak -t \"translate to kekSpeak text\""
}

tranlate()
{


}

if [ "$#" -lt 2 ] || ! [[ "$1" =~ ^(-f|-t)$ ]]; then help; exit 2; fi

if [ "$1" == "-t" ]; then tranlate "$2" "aeiou" "4310_";
else tranlate "$2" "4310_" "aeiou"; fi
