#!/bin/bash
for curArg in "$@"
do
  if ! [ -e "$curArg" ] || ! [ -d "$curArg" ]; then
  mkdir "$curArg"; fi
done
for curArgFirst in "$@"
do
  for curArgSecond in "$@"
  do
    if [ "$curArgFirst" != "$curArgSecond" ]; then
      rsync -a "$curArgFirst/" "$curArgSecond"
    fi
  done
done
