#!/bin/bash
# repository and android studio ide project sync
# can be added to startup

syncByName()
{
  if [ -f "./repoToASIDE.$1.conf" ]; then
    currentConfig="$(cat "./repoToASIDE.$1.conf")"
    pathToAndroidStudioProject="${currentConfig%.*}"
    pathToRepository="${currentConfig%*.}"
  else
    pathToAndroidStudioProject=""
    while [ -d "$pathToAndroidStudioProject" ]; do
      echo "Enter a path to android studio project $1:"
      read -r pathToAndroidStudioProject
    done
    pathToRepository=""
    while [ -d "$pathToRepository" ]; do
      echo "Enter a path to repository $1:"
      read -r pathToRepository
    done
    touch ./repoToASIDE.current
    echo "$pathToAndroidStudioProject.$pathToRepository" > "./repoToASIDE.$1.conf"
  fi

  rsync -avu --delete "$pathToRepository" "$pathToAndroidStudioProject"
}

for curRepo in "$@"; do
  syncByName "$curRepo"
done
